[package]
name = "tiny_gcs"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
description = "A (very) tiny GCS library"
license = "MIT/Apache-2.0"

[dependencies]
